version: '3.1'

services: 
  node-dev-manager-api: 
    container_name: node-dev-manager-api
    build: '.'
    volumes: 
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on: 
      - postgres-dev-manager-api
    networks: 
      - app-connect
    ports:
      - '3333:3333'

  postgres-dev-manager-api:
    container_name: postgres-dev-manager-api
    image: postgres:latest
    restart: unless-stopped
    volumes: 
      - postgres-dev-manager-data:/data
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - app-connect
    ports:
      - '5433:5432'

volumes: 
  postgres-dev-manager-data:
  
networks:
  app-connect:
    driver: bridge